### ISSUE TITLE
Subprocesses cannot publish to topics

### ISSUE THREAD

**Issue by heuristicus** [asmodehn/pyros#19]
While the origin of the issue is unclear, the reason why publishing is not possible is because the subscriber is not added to the publisher's list, and thus no messages are received. The `self.connections` variable in [`topics.py`](https://github.com/ros/ros_comm/blob/indigo-devel/clients/rospy/src/rospy/topics.py) of `rospy` is not updated in the subprocess.

Conclusion appears to be that because the monitoring of topics is happening in a separate thread (the one which is going through registration::RegManager::run, I think?), these new registrations do not end up in the memory of the subprocess, so the connections never appear there. 

`client::init_node` spawns several threads:
-  `init::start_node` line 312 calls `xmlrpc::XmlRpcNode::start`, which creates the thread to run the RPC server. 
-  line 337 starts the TCPROS server, calling `tcpros_base::start` which launches a thread to run the `run` function which accepts connections. Connections are then created on line 165, via the route `inbound_handler->tcpros_base::_tcp_server_callback->self.topic_connection_handler->tcpros_pubsub::TCPROSHandler::topic_connection_handler->topics::add_connection->tcpros_pubsub::QueuedConnection`

**Comment by heuristicus** [comment]
According to [this comment](https://github.com/ros/ros_comm/blob/78aa1c4ec879668f686aba873f52968b1bd7aa73/clients/rospy/src/rospy/topics.py#L146), topics and services can be initialised before the node - does this affect anything?

**Comment by heuristicus** [comment]
Information about added publishers or subscribers is sent to the master node [here](https://github.com/ros/ros_comm/blob/ace5b9c11af766564441bad2cb08f5fca5b73784/clients/rospy/src/rospy/impl/registration.py#L420).

**Comment by heuristicus** [comment]
`subscriber_listener` [here](https://github.com/ros/ros_comm/blob/78aa1c4ec879668f686aba873f52968b1bd7aa73/clients/rospy/src/rospy/topics.py#L805) is `None` when initialising the chatter topic in subprocess. Same when initialising publisher for the `process` topic in the main process, so maybe not important.

**Comment by heuristicus** [comment]
Might be able to use the `subscriber_listener` to trigger addition of the subscription topic to the connections list of the publisher?

Not sure if there is enough information there to add the subscriber manually - need a reference to the subscriber itself which does not seem to be present in [SubscribeListener](http://docs.ros.org/diamondback/api/rospy/html/rospy.topics.SubscribeListener-class.html).

**Comment by heuristicus** [comment]
`tcpros_base` is where checks are made to determine subscribers and publishers (?). This is run in a separate thread, with the `run` function, which runs until the node is shutdown.

**Comment by heuristicus** [comment]
`tcpros_pubsub::topic_connection_handler` is where connections for topics are created, both subscribers and publishers (?). Something happens here to do with connections...

**Comment by heuristicus** [comment]
`topics::TopicManager::acquire_impl` creates the subscriber/publisher.

Line 1149 `get_registration_listeners().notify_added(resolved_name, ps.type, reg_type)`  seems to be important, appears to call `reg_added` function of `registration::RegManager`, which informs the master about the new topic or subscriber. `publisher_update` is then called, which modifies the `updates` list.

**Comment by heuristicus** [comment]
@asmodehn looks like there's nothing we can do about this. I suppose we can close this.

**Comment by asmodehn** [comment]
@heuristicus yes lets keep fixing the current design then.
