### ISSUE TITLE
Clean up ros interface

### ISSUE THREAD

**Issue by heuristicus** [asmodehn/pyros#20]
Currently `add_topic` and `expose_topic` have very similar functionality, and having both makes things very confusing.

**Comment by asmodehn** [comment]
Hmmm we probably should refactor this part of the code... but before doing
that we should have all unit tests in place ( regarding parameters passing
/vs/ available topics/services ) to make sure we don't break anything in
the process.

**Comment by asmodehn** [comment]
The interface has been changed as part of the refactoring to 0.1
