### ISSUE TITLE
Service not coming back up

### ISSUE THREAD

**Issue by asmodehn** [asmodehn/pyros#21]
It seems there is a problem in the way services are handled :

I want to expose /my_service but it is not present yet -> waiting list.
/my_service appears in ROS system
It is detected and exposed as expected.
It disappears -> not exposed anymore
It reappears in ROS -> it is NOT exposed ( but should be )

We should probably write a unit test for this use case too.
@heuristicus please have a look at it while looking into these dynamic parameters and writing tests.

**Comment by heuristicus** [comment]
Might not be entirely related, but [this](https://github.com/asmodehn/rostful-node/blob/54e84243617f0d0e1a6d56a3d1bc46e4a0c4d528/src/rostful_node/ros_interface.py#L132) initialisation of the `ServiceBack` looks like it will be incorrect if the service is not running on startup.
