### ISSUE TITLE
Using rostopic echo or creating an additional instance of a topic causes it to be removed from the topic list

### ISSUE THREAD

**Issue by heuristicus** [asmodehn/pyros#27]
Reproduce: run the web interface, and echo a topic that already exists on the system - it will probably be put into the waiting list.

**Comment by asmodehn** [comment]
This has probably been fixed.
Need to confirm and close.

**Comment by asmodehn** [comment]
Tested and I cannot reproduce anymore. the bug has likely been fixed. closing.
