### ISSUE TITLE
Wise to have generated copies of rapp services here?

### ISSUE THREAD

**Issue by stonier** [asmodehn/pyros#56]
The StartRapp, etc....

**Comment by asmodehn** [comment]
There is some duplicated | dead code since pyros has been changing quite a lot for ROS and the rocon ( rapp + interactions ) part hasn't been kept uptodate.
Anyway it will need review and cleanup for sure.

**Comment by asmodehn** [comment]
Planning to drop Rocon support https://github.com/asmodehn/pyros/issues/61
